version: "3.8"

services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: asir_openldap
    environment:
      LDAP_ORGANISATION: ${LDAP_ORGANISATION}
      LDAP_DOMAIN: ${LDAP_DOMAIN}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      LDAP_TLS: "false"
    volumes:
      - ./docker/ldap/data:/var/lib/ldap
      - ./docker/ldap/config:/etc/ldap/slapd.d
    ports:
      - "389:389"
    restart: unless-stopped
    networks:
      - asir_net

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: asir_phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ${PHPLDAPADMIN_LDAP_HOSTS}
      PHPLDAPADMIN_HTTPS: ${PHPLDAPADMIN_HTTPS}
    ports:
      - "8090:80"
    depends_on:
      - openldap
    restart: unless-stopped
    networks:
      - asir_net

networks:
  asir_net:
    driver: bridge

